-
  name: Dependency
  hosts: all
  tasks: 
    - name: yum update 
      yum:
        update_only:
        state: latest
    - name: Install Dependency
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - epel-release
        - httpd
        - rsync
        - screen
        - zip
        - unzip
        - git
        - wget
        - yum-utils
    - name: Install Repo 
      yum:
        name: https://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm
        state: present
    - name: Install Mysql Client
      yum:
        name: mysql-server
        state: present
    - name: Install PHP 7.0 Remi Repo
      yum: 
        name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
        state: present
    - name: Enable Repo PHP 7.0
      shell: yum-config-manager --enable remi-php70
    - name: Install PHP Jojonomic
      yum:
        name: "{{ jojonomicphp }}"
        state: present
      vars:
        jojonomicphp:
        - php 
        - php-bcmath 
        - php-bz2 
        - php-calendar 
        - php-core
        - php-ctype 
        - php-curl 
        - php-date 
        - php-dom 
        - php-exif 
        - php-fileinfo 
        - php-filter
        - php-ftp 
        - php-gd 
        - php-gettext 
        - php-gmp 
        - php-hash 
        - php-iconv 
        - php-igbinary
        - php-intl 
        - php-json 
        - php-ldap 
        - php-libxml 
        - php-mbstring 
        - php-mcrypt
        - php-mongodb 
        - php-mysqli 
        - php-openssl 
        - php-pcntl 
        - php-pcre 
        - php-pdo 
        - php-mysql
        - php-phar 
        - php-posix 
        - php-readline 
        - php-reflection 
        - php-session 
        - php-shmop
        - php-xml 
        - php-sockets 
        - php-spl 
        - php-sqlite3 
        - php-standard 
        - php-sysvmsg 
        - php-sysvsem 
        - php-sysvshm 
        - php-tokenizer 
        - php-wddx 
        - php-xml 
        - php-xmlreader
        - php-xmlwriter 
        - php-xsl 
        - php-opcache 
        - php-zip 
        - php-zlib

         
  

  
