-
  name: Dependency
  hosts: all
  tasks:
    - name: yum update 
      yum:
        update_only:
        state: latest
  tasks:
    - name: Install Dependency
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - epel-release
        - httpd
        - rsync
        - screen
        - zip
        - unzip
        - git
        - wget

  
